name: example
description: An example that demonstrates how to load a configuration file via HTTP in the browser.
repository: https://github.com/just95/toml.dart/tree/main/example/http_config_loader
publish_to: none
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  toml:
    path: ../../
dev_dependencies:
  # Dependencies for `webdev`.
  # See also https://dart.dev/tools/webdev#depending-on-build_-packages.
  build_runner: any
  build_web_compilers: any
  # Dependencies for `dartanalyzer`.
  pedantic: ^1.9.2
