name: example
description: An example that demonstrates how to load a configuration file via HTTP in the browser.
repository: https://github.com/just95/toml.dart/tree/main/example/http_config_loader
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  toml:
    path: ../../
dev_dependencies:
  # Dependencies for `webdev`.
  # See also https://dart.dev/tools/webdev#depending-on-build_-packages.
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  # Dependencies for `dartanalyzer`.
  lints: ^2.0.0
  analyzer: any
  # Dependencies for continuous integration.
  webdriver: ^3.0.2
  shelf: ^1.4.0
  shelf_static: ^1.1.1
