name: flutter_example
description: An example that demonstrates how to load a configuration file from an asset in Flutter.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  toml:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/example.toml
