name: example
description: An example that demonstrates how to decode a TOML document from a string.
repository: https://github.com/just95/toml.dart/tree/main/example/toml_parser
publish_to: none
environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  toml:
    path: ../../
dev_dependencies:
  lints: ^5.1.1
