name: example
description: An example that demonstrates how to save a configuration file to a local file.
repository: https://github.com/just95/toml.dart/tree/main/example/filesystem_config_saver
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  toml:
    path: ../../
dev_dependencies:
  pedantic: ^1.11.0
