name: example
description: An example that demonstrates how to save a configuration file to a local file.
repository: https://github.com/just95/toml.dart/tree/main/example/filesystem_config_saver
publish_to: none
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  toml:
    path: ../../
dev_dependencies:
  lints: ^2.0.0
